### ISSUE TITLE
gem does not understand stream type "other", i.e. timecode

### ISSUE THREAD

**Issue by tilllt** [greatseth/mediainfo#16]
/Library/Ruby/Gems/2.0.0/gems/mediainfo-0.7.2/lib/mediainfo.rb:182:in `create': bad stream type: "Other" (Mediainfo::Stream::InvalidStreamType)

Other
ID                                       : 2
Type                                     : Time code
Format                                   : QuickTime TC
Duration                                 : 5s 0ms
Time code of first frame                 : 00:00:05:00
Time code settings                       : Striped
Language                                 : English
Encoded date                             : UTC 2013-10-25 12:52:10
Tagged date                              : UTC 2013-10-25 12:52:10

**Comment by NorseGaud** [comment]
Can you provide the full XML from the mediainfo command?

**Comment by NorseGaud** [comment]
Will be handled in 1.0.0
