### ISSUE TITLE
Fails for timecode

### ISSUE THREAD

**Issue by hadmut** [greatseth/mediainfo#17]
Hi, 

mediainfo issues the following section for videos with a timecode, e.g. from a GoPro:

Other
ID                                       : 3
Type                                     : Time code
Format                                   : QuickTime TC
Duration                                 : 46s 263ms
Title                                    : GoPro TCD
Language                                 : English
Encoded date                             : UTC 2015-12-01 07:14:39
Tagged date                              : UTC 2015-12-01 07:14:39

This causes the gem to abort with

Error bad stream type: "Other"
Mediainfo::Stream::InvalidStreamType
/var/lib/gems/1.9.1/gems/mediainfo-0.7.2/lib/mediainfo.rb:182:in `create'
/var/lib/gems/1.9.1/gems/mediainfo-0.7.2/lib/mediainfo.rb:495:in`block in parse!'
/usr/lib/ruby/1.9.1/rexml/element.rb:905:in `block in each'
/usr/lib/ruby/1.9.1/rexml/xpath.rb:67:in`each'
/usr/lib/ruby/1.9.1/rexml/xpath.rb:67:in `each'
/usr/lib/ruby/1.9.1/rexml/element.rb:905:in`each'
/var/lib/gems/1.9.1/gems/mediainfo-0.7.2/lib/mediainfo.rb:494:in `parse!'
/var/lib/gems/1.9.1/gems/mediainfo-0.7.2/lib/mediainfo.rb:412:in`raw_response='
/var/lib/gems/1.9.1/gems/mediainfo-0.7.2/lib/mediainfo.rb:405:in `initialize'

**Comment by NorseGaud** [comment]
Can you provide me with the full Mediainfo output from STDOUT? Thanks!

**Comment by NorseGaud** [comment]
Will be addressed in 1.0.0 release
