### ISSUE TITLE
"backward incompatibility" issue with latest CLI

### ISSUE THREAD

**Issue by glydeck** [greatseth/mediainfo#19]
I wanted to inform you about a "backward incompatibility" with the latest version of the MediaInfo CLI and the latest version of this Gem.
The CLI version [MediaInfo Command line, MediaInfoLib - v0.7.82] works with the 0.7.2 gem.
But with CLI version [MediaInfo Command line, MediaInfoLib - v0.7.95] intalled, when querying a WAVE file's duration from the gem, the following error is thrown:
/Library/Ruby/Gems/2.0.0/gems/mediainfo-0.7.2/lib/mediainfo/attr_readers.rb:60:in `block (2 levels) in mediainfo_duration_reader': unexpected time fragment! please report bug! (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/mediainfo-0.7.2/lib/mediainfo/attr_readers.rb:51:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/mediainfo-0.7.2/lib/mediainfo/attr_readers.rb:51:in `block in mediainfo_duration_reader'
	from /Library/Ruby/Gems/2.0.0/gems/mediainfo-0.7.2/lib/mediainfo/attr_readers.rb:36:in `block in mediainfo_attr_reader'

**Comment by NorseGaud** [comment]
Thanks, I'll attempt to find a solution.

**Comment by NorseGaud** [comment]
Can you provide your xml for me from the video?

**Comment by NorseGaud** [comment]
Eliminated need for attr_readers, so this should be resolved. Once we release 1.0.0 and you still have the issue, please re-open a new issue. Release will be in a week or so.
