### ISSUE TITLE
ArgumentError (Bad Input) when providing filename

### ISSUE THREAD

**Issue by rgaufman** [greatseth/mediainfo#27]
I'm getting this when I try to use a filename:

```ruby
irb(main):003:0> media_info = MediaInfo.from('bad-video-hikvision.mkv')
Traceback (most recent call last):
        3: from /usr/bin/irb:11:in `<main>'
        2: from (irb):3
        1: from /var/lib/gems/2.5.0/gems/mediainfo-1.0.1/lib/mediainfo.rb:84:in `from'
ArgumentError (Bad Input)
Input must be:
A video or xml file location. Example: '~/videos/test_video.mov' or '~/videos/test_video.xml'
A valid URL. Example: 'http://www.site.com/videofile.mov'
Or MediaInfo XML
```

However, this works:
```
irb(main):004:0> media_info = MediaInfo.from('./bad-video-hikvision.mkv')
```

It would be good if a filename can be provided without ./

**Comment by NorseGaud** [comment]
Yep, I agree. 
`elsif input.include?('/')
        @file = ::File.expand_path input # turns ~/path/to/file into /home/user/path/to/file
        raise ArgumentError, 'You must include a file location.' if @file.nil?
        raise ArgumentError, "need a path to a video file, #{@file} does not exist" unless ::File.exist? @file
        @file_path = ::File.dirname  @file
        @filename = ::File.basename @file
        @escaped_input = @file.shell_escape_double_quotes
        # Set variable for returned XML`

The above section is after it checks for raw XML, a URL, and then an .xml file to open. Maybe changing input.include?('/') to match a regex instead? I can take a look after the holiday, but if you have any suggestions on the regex, please let me know (or do a pull request).

**Comment by NorseGaud** [comment]
Ok, had some time to fix this. It'll be in 1.0.2
