### ISSUE TITLE
MediaInfo::EnvironmentError (/usr/local/bin/mediainfo cannot be found. Are you sure mediainfo is installed?)

### ISSUE THREAD

**Issue by rgaufman** [greatseth/mediainfo#28]
I have mediainfo installed:

``` bash
$ which mediainfo
/usr/bin/mediainfo
$ /usr/bin/env mediainfo --version
MediaInfo Command line,
MediaInfoLib - v0.7.82
```

However the gem is looking for it in the wrong place:
```ruby
irb(main):004:0> media_info = MediaInfo.from('./bad-video-hikvision.mkv')
Traceback (most recent call last):
        5: from /usr/bin/irb:11:in `<main>'
        4: from (irb):4
        3: from /var/lib/gems/2.5.0/gems/mediainfo-1.0.1/lib/mediainfo.rb:86:in `from'
        2: from /var/lib/gems/2.5.0/gems/mediainfo-1.0.1/lib/mediainfo.rb:45:in `run'
        1: from /var/lib/gems/2.5.0/gems/mediainfo-1.0.1/lib/mediainfo.rb:12:in `location'
MediaInfo::EnvironmentError (/usr/local/bin/mediainfo cannot be found. Are you sure mediainfo is installed?)
```

It would be good if it would find it using /usr/bin/env and only fallback to the hardcoded path.

**Comment by Dielerorn** [comment]
Is there a fix for this? Mine is installed to `/usr/bin/mediainfo` as well. I'm running v18.08.1

**Comment by stan3** [comment]
https://stackoverflow.com/questions/2108727/which-in-ruby-checking-if-program-exists-in-path-from-ruby has a discussion on how to search the path.  Can we use something from here?  Perhaps the ptools gem?

**Comment by NorseGaud** [comment]
Including this in the next release. Thanks for the great code @tbhi
