### ISSUE TITLE
CI & CodeClimate integrations

### ISSUE THREAD

**Issue by 01max** [greatseth/mediainfo#33]
Since those are both free for open source projects, could we add : 
- a CI service (such as https://travis-ci.org) in order to run specs automatically every time a PR is submitted.
- CodeClimate (with Rubocop) in order to easily **improve** & **keep an eye** on the code maintainability and complexity,  and the tests coverage.

I don't have the right on this repo myself to *"PR"* these integrations. 
I would be okay to improve the code based on CodeClimate's & Rubocop's advices for maximum availability if you are ok with integrating those.

**Comment by NorseGaud** [comment]
Sorry Max, I'm in a big career transition for the next month. I'm totally on board, but won't have any time to help. I trust you, so I can add your permissions to modify the master branch. Thanks!

**Comment by greatseth** [comment]
Hello, project enthusiasts!

@01max, if you want to put together a pull request with the changes needed for this stuff, that would be great. If I fall into a pothole, I imagine @NorseGaud will get it eventually, but I can try to pull it in the meantime.

**Comment by greatseth** [comment]
@01max Do you need myself or somebody ostensibly in charge of things on this side to setup accounts first?

**Comment by 01max** [comment]
Hi @greatseth !

Yes, you need to sign-up to https://travis-ci.org and give access to the repository, and then configure it (they are a GitHub-integrated service, so you need to have specifics rights on a repository to access it on travis).

For [CodeClimate](https://codeclimate.com/oss/), you will need to signup with GitHub too and active rubocop in the config.

There is no need for a pull request (at least before), it's only time spent configuring and testing directly on their websites. After these are integrated there will be pull requests to improve the codebase.

Since @NorseGaud won't be available for the next few weeks/months, I hope you will have the time to take a look at this (and know that I'm here if you want me to check it myself).

**Comment by 01max** [comment]
Any news on this subject?

**Comment by greatseth** [comment]
Hi @01max,

Sorry to leave you hanging.

I did the basic setup in both services. It looks like a few things need shuffling around for Travis to get going, but I'm on it...

**Comment by greatseth** [comment]
I have basic Travis integration going, but the tests which expect to find `mediainfo` present in the environment are failing. Does anyone have thoughts on the best way to address that? Is there something we can do on the Travis side? Or should we bundle a binary for use in tests? Something else?

**Comment by greatseth** [comment]
CodeClimate thinks we smell a little, but it doesn't look like it's anything too serious. ;)

**Comment by NorseGaud** [comment]
Thanks for jumping on this Seth. I believe it should pull the PR's committed code, `gem build` + `gem install`, and then run the tests.

BTW: I just moved to my new house and start my new job tomorrow. I'll be unable to focus on anything for another solid month.

**Comment by greatseth** [comment]
Congrats, @NorseGaud!

The Ruby environment setup seems to be getting set up just fine. I then added config to install `mediainfo` via `apt-get`. That appears to be working without error, but I haven't yet figured out how to get the `MEDIAINFO_PATH` environment variable set in a way that will be available in the test runs. I tried the config currently in `master` as well as the Travis settings interface for adding environment variables. Both options cause the job runner to show that it is setting the variable, but the tests dependent on being able to find `mediainfo` nonetheless fail with a message saying they were trying to find `mediainfo` in the default location rather than the custom one I am trying to specify.

I'm going to put this down for the moment, but we are almost there. If anybody has insights into how to get this last piece working, please let us know!

**Comment by NorseGaud** [comment]
Oh, you meant the mediainfo service. My bad. And thanks for the congrats.

How is Travis executing the tests? Rake? Or the rspec command? Both should use ENV, so that’s an interesting problem...

**Comment by 01max** [comment]
Thanks @greatseth !

It's my turn to be moving & unavailable for some time (until mid-December).
I will look at the Travis config issue if it's not fixed by then.

@greatseth could you also activate the rubocop plugin in code climate ?

**Comment by NorseGaud** [comment]
@greatseth @01max, got it working: https://travis-ci.org/greatseth/mediainfo
Was able to solve two issues and also simplify things a bit for users.
