### ISSUE TITLE
error handling an S3 signed URL

### ISSUE THREAD

**Issue by jasonsof** [greatseth/mediainfo#37]
Hi trying to get the mediainfo of a file on AWS S3 using a signed URL (code shown below) but am getting the error 

> MediaInfo::RemoteUrlError: HTTP call to xxxxxxxx is not working!.

  I know the URL is accessible because I can access it through a browser (it initiates a download).  Also, I think it should work since the mediainfo command line (MediaInfoLib - v18.12) works and returns the JSON, using this command:

    mediainfo --Output=JSON https://eu-west-1-xxxxxxx

Here's what I'm doing with Ruby

    s3_resource = Aws::S3::Resource.new(region: AWS_REGION)
    obj = s3_resource.bucket(BUCKET_NAME).object(s3_name)

    signed_url = obj.presigned_url(:get, expires_in: 3600)

    media_info = MediaInfo.from(signed_url)

the result is 

    MediaInfo::RemoteUrlError: HTTP call to xxxxxxxx is not working!

I'm using mediainfo gem (1.1.2), aws-sdk (2.11.58) and ruby-2.3.1 if it helps at all

**Comment by NorseGaud** [comment]
Sorry for the wait. I'll get to this in a few days

**Comment by NorseGaud** [comment]
Can you try Mediainfo.from_link instead of .from?
The .from method will try and automatically match. Also, try the newest release of the gem.

**Comment by jasonsof** [comment]
Hi thanks for getting back to me on this.

I'm using mediainfo 1.2.0 now and using Mediainfo.from_link now instead I'm still seeing the same result:

MediaInfo::RemoteUrlError: HTTP call to https://xxxxxxx is not working!

(using the command line mediainfo using the same URL works)

**Comment by NorseGaud** [comment]
Interesting... I'd like to replicate this so I can create a test for it and then the code to fix it. I'm a bit overwhelmed at work, so it won't be likely until Monday. Thanks for the report!

**Comment by jasonsof** [comment]
No worries, thanks for looking into it!

**Comment by NorseGaud** [comment]
Hey @jasonsof, so I noticed that there were a few problems with 1.2.0 that I've been able to resolve in 1.2.1. Please grab that version for me and then try again: I've added better reporting as to why you're unable to use a signed s3 object url. Let me know what it's showing.

I realized that trying to test signed s3 urls would require the s3 sdk gem and bloat things a lot. I want to avoid that bloat if possible. My hypothesis right now is that the signed url does some sort of redirection that's not understood by the `from_uri` Net::HTTP code we currently use. I screwed up my AWS account so I can't test any further for the next few days. Can you try something like https://stackoverflow.com/questions/6934185/ruby-net-http-following-redirects before passing it to the mediainfo method?

**Comment by jasonsof** [comment]
Hi @NorseGaud thanks for the update.

I've tried some things out with the latest version. The result is now `Net::HTTPServerException: 403 "Forbidden"` using both `.from_link` and `.from`

I've also tried some methods of getting to the final redirect URL with the same result as above.

Something else I tried, was doing a standard CURL to that url and the first few lines might shed some more light on what's going on which fits with the `403` error.  It looks like there is a handshake going on to establish SSL before anything happens.  I'm not sure how the mediainfo CLI handles this and works but maybe that is the missing piece?

```
[jason:~/Sites/rails/test]$ curl -v -X GET "https://eu-west-1-jason.s3.eu-west-1.amazonaws.com/1/file.mp4?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=xxxx&X-Amz-Date=20190313T103127Z&X-Amz-Expires=3600&X-Amz-Security-Token=xxxx&X-Amz-SignedHeaders=host&X-Amz-Signature=xxxx"
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 52.218.37.200...
* TCP_NODELAY set
* Connected to eu-west-1-jason.s3.eu-west-1.amazonaws.com (xx.xxx.xx.xxx) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=Washington; L=Seattle; O=Amazon.com Inc.; CN=*.s3-eu-west-1.amazonaws.com
*  start date: Nov  8 00:00:00 2018 GMT
*  expire date: Nov  6 12:00:00 2019 GMT
*  subjectAltName: host "eu-west-1-jason.s3.eu-west-1.amazonaws.com" matched cert's "*.s3.eu-west-1.amazonaws.com"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert Baltimore CA-2 G2
*  SSL certificate verify ok.
> GET /1/file.mp4?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=xxxx&X-Amz-Date=20190313T103127Z&X-Amz-Expires=3600&X-Amz-Security-Token=xxxx&X-Amz-SignedHeaders=host&X-Amz-Signature=xxxx HTTP/1.1
> Host: eu-west-1-jason.s3.eu-west-1.amazonaws.com
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< x-amz-id-2: xxxx
< x-amz-request-id: xxxx
< Date: Wed, 13 Mar 2019 10:48:10 GMT
< x-amz-replication-status: COMPLETED
< Last-Modified: Wed, 13 Mar 2019 10:10:39 GMT
< ETag: "84aed97aa29c6e020a34d549247893df"
< x-amz-server-side-encryption: AES256
< x-amz-meta-upload_batch_id: 04407802-b738-43cf-a514-8f7dfcfe3170
< x-amz-version-id: VSU5vPICKkMSaY7pmjqBDozIdK0OBnhn
< Accept-Ranges: bytes
< Content-Type: video/mp4
< Content-Length: 4167696
< Server: AmazonS3
```

I understand not wanting to add bloat to the gem - I think that the aws-sdk v3 is now completely modular so you can pick and choose services, you may only need aws-sdk-core but this is your call :)
Thanks again for the help

**Comment by NorseGaud** [comment]
Finally got my aws account back! I played around with it this morning and found the problem. I'll finish testing hopefully before the end of the weekend and let you know when there is a new release ready. Thanks for the patience.

**Comment by NorseGaud** [comment]
https://github.com/greatseth/mediainfo/pull/42

**Comment by NorseGaud** [comment]
Alright, 1.3.0 has been released. Let me know if it works for you.

**Comment by jasonsof** [comment]
Sorry to be sending you another error message :( I'm getting this now: `NameError: uninitialized constant MediaInfo::Open3`

(using the `from` method)

I saw you added a spec and that this should work. Is there something I'm doing wrong here?

**Comment by NorseGaud** [comment]
You’re right, I see what’s wrong. I’ll have a patch in soon

**Comment by NorseGaud** [comment]
Sorry about that. Try 1.3.1. I had some weird environment issues locally letting open3 work without the require.

**Comment by jasonsof** [comment]
Hi @NorseGaud I'm now seeing this:

```
2.3.1 :007 > media_info = MediaInfo.from_link(signed_url)
MediaInfo::ExecutionError: Execution of '/usr/local/bin/mediainfo 'https://eu-west-1-xxxx.amazonaws.com/file.mp4?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=xxx&X-Amz-Date=20190318T094100Z&X-Amz-Expires=3600&X-Amz-Security-Token=xxxx&X-Amz-SignedHeaders=host&X-Amz-Signature=xxx' --Output=XML' failed:
 E: https://eu-west-1-xxxx.amazonaws.com/file.mp4?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=xxx&X-Amz-Date=20190318T094100Z&X-Amz-Expires=3600&X-Amz-Security-Token=xxxx&X-Amz-SignedHeaders=host&X-Amz-Signature=xxx, HTTP server doesn't seem to support byte ranges. Cannot resume.
```

does this test of yours pass? https://github.com/greatseth/mediainfo/blob/92d45b4dfc3022b9cb6d11a41b67393847f1cccc/spec/spec_shared_examples.rb#L52

If it does I wonder if something needs to configured in S3 on my end to allow this to work... I'll check on S3 bucket properties to see if there is something about supporting byte ranges

**Comment by NorseGaud** [comment]
Yep, the test I wrote for this works. I didn’t do anything special to the bucket either.

If you want, you could email me your full URL with a temporary and limited read only access key/secret to test with. I’ll run it on my end and see if I get the same results: connarpierce@gmail.com

**Comment by NorseGaud** [comment]
After a bit of banging my head against the keyboard, I noticed that the return code of the error is 0, which means that what we're seeing isn't an error at all, just a message, and my logic on whether to raise a failure was flawed. I'll get 1.3.1 out soon with the fix.

**Comment by NorseGaud** [comment]
Ok, 1.3.2 ready to go!
