### ISSUE TITLE
MediaInfo.from_string mistakes local file paths for remote link URLs

### ISSUE THREAD

**Issue by tomichal** [greatseth/mediainfo#38]
`MediaInfo.from('/some/path/some-file-name-with-colon:like-this.txt')` will internally call `MediaInfo.from_link` instead of `MediaInfo.from_local_file`.

**Comment by NorseGaud** [comment]
Why would you have a colon in a filename? I don't believe that's allowed in windows, though, linux doesn't prohibit it. How many files do you deal with like this?

**Comment by tomichal** [comment]
It’s a MacOS system with multitude of files. We don’t have control over the names. Users can save them as they please and apparently some like to have names with colons. 

It’s really no big deal to us since I switched to using the .from_local_file method (unless we end up allowing remote and local locations in which case being able to always use .from would be handy).

Anyhow, just thought would let you guys know of this edge case and thanks for putting this useful gem out there!

**Comment by NorseGaud** [comment]
Ah, yep, I can see that being a big concern then. I'll add some logic for this in the next release. Thanks!
