### ISSUE TITLE
Mediainfo custom path not working

### ISSUE THREAD

**Issue by valencar** [greatseth/mediainfo#48]
Although we set the path by using MEDIAINFO_PATH, there is a check on the .location method where it tries `which('mediainfo')` no matter what.

So, even though we specified the custom path, it tries to find the original one from PATH. 

My use case is a Lambda function, so I won't change the original PATH, but rather use the mediainfo binary located in my project.

```
[5] pry(main)> ::MediaInfo.location
MediaInfo::EnvironmentError: MediaInfo binary cannot be found. Are you sure mediainfo is installed?
from /Users/victoralencar/projects/mlabs/uploader/vendor/bundle/ruby/2.5.0/gems/mediainfo-1.3.3/lib/mediainfo.rb:29:in `location'
[6] pry(main)> ::File.exist? 'lib/mediainfo'
=> true
```

https://github.com/greatseth/mediainfo/blob/master/lib/mediainfo.rb#L29

Please correct me if I am wrong. Thanks!

**Comment by NorseGaud** [comment]
Yup! Totally see that. Good catch! Want to do a PR for it? I can get to it next weekend otherwise.

**Comment by valencar** [comment]
Sure. I believe this would be the fix, https://github.com/greatseth/mediainfo/pull/49. I will test this version on Lambda.

**Comment by NorseGaud** [comment]
1.4.0 released

**Comment by NorseGaud** [comment]
@valencar Things working using 1.4.0?

**Comment by valencar** [comment]
Yeah, seems to be working fine! Thanks for the quick release @NorseGaud
